apiVersion: v1
kind: Service
metadata:
  name: connexion-loadbalancer
  labels:
    app: connexion
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    app: connexion
  type: LoadBalancer
